### ISSUE TITLE
:running_man: To disable .swp files in vim :muscle:

### ISSUE THREAD

**Issue by rayluo** [rayluo/home#1]
Let's do it! 💪

**Comment by ulidtko** [comment]
Heyy :wink: This is done via `set noswapfile`... Check out [my vimrc](https://github.com/ulidtko/versioned-configs/blob/master/HOME/vim/vimrc) too — and have a good day!

**Comment by rayluo** [comment]
@ulidtko Thanks for the hint! I knew it can be done but I was hesitating. Even though those 2 reasons for swap files (quoted from [here](https://vi.stackexchange.com/a/179)):

> 1. Swap files store changes you've made to the buffer. If Vim or your computer crashes, they allow you to recover those changes.
> 2. Swap files also provide a way to avoid multiple instances of Vim from editing the same file. This can be useful on multi-user systems or just to know if you have another Vim already editing a file.

are not applicable to me, the by-product of the 2nd point could still be helpful. Because my working pattern is to open multiple terminals, one per project (i.e. repo); each project has its own Session.vim, and I use one vim per project. When/if I accidentally open same file in different vim, the existing swp file causes vim to give me a warning UPFRONT, so that I could proceed accordingly (either abort, or proceed with open read-only). If I turn off swp file, vim will only give a warning when you are about to save content in the 2nd vim, which might be too late.

That being said, perhaps that concern would be mitigated by `git stash` pre-existing changes via a new terminal, and then go back to 2nd vim and save, and then rely on versioning system to have a nasty diff. I need to have a trade-off between the 2 alternatives here.

Perhaps @ulidtko you've long been over that hump, because [you've turned off swp for 6 years](https://github.com/ulidtko/versioned-configs/blame/master/HOME/vim/vimrc#L24).

PS: Congrats on picking up the markdown word-diff idea, and thanks for your implementation!

**Comment by ulidtko** [comment]
Okay, I see your reasons.

I did turn on `swapfile` temporarily a couple of times — on those rare occasions when opening *huge*, multi-GiB-size files was needed. Vim shines at tackling those beasts.

You can `git stash`, yes — but also `git add -p`/`git reset -p` might be enough. The staging/index area of git is sort of a shadow copy of the working tree, I use it all the time that way; `git commit -a` doesn't even hit my shell history.

One more thing... in those project-style workflows where vim sessions are commonly used (contrasted to single-file stuff) — I found myself needing a *dedicated window*, to single out the one or two important contexts apart from zillions of terminal tabs, ssh & tmux sessions, etcetera. I've been using Atom for some years just for this purpose (a dedicated project-work window); after having ditched it, I'm using Neovim-Qt. And somehow, *it picks up parallel changes to open files*, in undo-able fashion, as soon as you focus back into its window. Not sure but if memory serves, I didn't explicitly set up any of that via vimrc.

On markdown word-diff — thanks; that was just a really nice idea, I appreciate you sharing it and in turn benefiting from my implementation :) Best wishes
